In [1]:
print("hello")

hello

In [1]:
import pandas as pd
import numpy as np

In [2]:
df= pd.read_csv("d:/Machine_learning/data/covid_toy.csv")

In [3]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=.2)

In [6]:
x_train

    age  gender  fever   cough       city
54   60  Female   99.0    Mild     Mumbai
18   64  Female   98.0    Mild  Bangalore
90   59  Female   99.0  Strong      Delhi
7    20  Female    NaN  Strong     Mumbai
67   65    Male   99.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
86   25    Male  104.0    Mild  Bangalore
49   44    Male  104.0    Mild     Mumbai
34   74    Male  102.0    Mild     Mumbai
65   69  Female  102.0    Mild  Bangalore
3    31  Female   98.0    Mild    Kolkata

[80 rows x 5 columns]

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

In [ ]:
transformer = ColumnTransformer(transformers=[
    ('tf1', SimpleImputer(), ['fever']),
    ('tf2', OrdinalEncoder(categories=[["Mild", "Strong"]]), ['cough']),
    ('tf3', OneHotEncoder(sparse_output=False, drop='first'), ['gender', 'city'])
],remainder='passthrough')

In [9]:
transformer.fit_transform(x_train).shape

(80, 6)

In [10]:
transformer.transform(x_test).shape

(20, 6)