In [1]:
print("hello")

hello

In [15]:
import pandas as pd
import numpy as np

In [3]:
employee_database = {
    "emp_id": [101, 102, 103],
    "name": ["Alice Smith", "Bob Jones", "Charlie Brown"],
    "role": ["Software Engineer", "HR Manager", "Data Analyst"],
    "salary": [85000, 75000, 80000]
}

In [5]:
df=pd.DataFrame(employee_database)

In [9]:
df

   emp_id           name               role  salary
0     101    Alice Smith  Software Engineer   85000
1     102      Bob Jones         HR Manager   75000
2     103  Charlie Brown       Data Analyst   80000

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   emp_id  3 non-null      int64
 1   name    3 non-null      str
 2   role    3 non-null      str
 3   salary  3 non-null      int64
dtypes: int64(2), str(2)
memory usage: 228.0 bytes

In [ ]:
# 3index=false , not create index
df.to_csv("employee.csv")

In [18]:
# series is data strcuture
ser=pd.Series(np.random.rand(34))

In [19]:
ser

0     0.530955
1     0.311168
2     0.504058
3     0.032361
4     0.218543
5     0.621988
6     0.227253
7     0.982799
8     0.042755
9     0.640320
10    0.610647
11    0.243442
12    0.499350
13    0.365884
14    0.909583
15    0.932670
16    0.755919
17    0.238967
18    0.774569
19    0.128082
20    0.924354
21    0.660317
22    0.908496
23    0.837708
24    0.816972
25    0.792286
26    0.285561
27    0.909649
28    0.421320
29    0.890392
30    0.882413
31    0.506658
32    0.708531
33    0.430496
dtype: float64

In [24]:
newdf= pd.DataFrame(np.random.rand(334,5),index=np.arange(334))

In [26]:
newdf.head()

          0         1         2         3         4
0  0.614240  0.331700  0.629105  0.056025  0.488052
1  0.151019  0.268798  0.245516  0.943052  0.736228
2  0.318310  0.679584  0.350518  0.307316  0.252943
3  0.140717  0.818637  0.351302  0.128759  0.873878
4  0.899799  0.409818  0.201427  0.260245  0.916590

In [31]:
# row=1,col=0
newdf.sort_index(axis=0,ascending=False)

            0         1         2         3         4
333  0.642879  0.741656  0.641609  0.801047  0.136532
332  0.482371  0.609582  0.754708  0.822763  0.362133
331  0.926035  0.875049  0.868886  0.192747  0.843444
330  0.869073  0.421332  0.811011  0.236004  0.763630
329  0.074885  0.540028  0.567163  0.935527  0.745885
..        ...       ...       ...       ...       ...
4    0.899799  0.409818  0.201427  0.260245  0.916590
3    0.140717  0.818637  0.351302  0.128759  0.873878
2    0.318310  0.679584  0.350518  0.307316  0.252943
1    0.151019  0.268798  0.245516  0.943052  0.736228
0    0.614240  0.331700  0.629105  0.056025  0.488052

[334 rows x 5 columns]

In [32]:
newdf[0]

0      0.614240
1      0.151019
2      0.318310
3      0.140717
4      0.899799
         ...
329    0.074885
330    0.869073
331    0.926035
332    0.482371
333    0.642879
Name: 0, Length: 334, dtype: float64